// <auto-generated />
using Inventory_Management_System.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory_Management_System.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231229144855_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory_Management_System.Models.Inventory", b =>
                {
                    b.Property<int>("Id_Inventory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Inventory"));

                    b.Property<string>("Name_Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity_Products")
                        .HasColumnType("integer");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Inventory");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("Inventory_Management_System.Models.Products", b =>
                {
                    b.Property<int>("Id_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Product"));

                    b.Property<string>("Description_Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacture_Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name_Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price_Product")
                        .HasColumnType("double precision");

                    b.HasKey("Id_Product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Inventory_Management_System.Models.User", b =>
                {
                    b.Property<string>("User_Name")
                        .HasColumnType("text");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User_Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("User_Name");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
